# Generated by Django 4.2.4 on 2023-08-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
