# Generated by Django 4.2.4 on 2023-08-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registration_completed',
            field=models.BooleanField(default=False),
        ),
    ]
